/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blutzerz.ftpclient;

import java.io.IOException;
import java.util.Collection;

import org.apache.commons.net.ftp.FTPFile;

import com.blutzerz.ftpclient.engine.FTPEngine;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());

        FTPEngine ftp = new FTPEngine(
            "files.000webhost.com", 
            21, 
            "blutzerz-ftp-client-test", 
            "tNb2dRx![2Qw7LUf24");

            
        ftp.open();
        ftp.changeDirectory("/public_html");
        ftp.uploadFile("G:/img1.jpg");
        for(FTPFile ftpFile : ftp.getFilesDirectory()){
            System.out.println(ftpFile.getName());
        }
        ftp.downloadFile(".htaccess", "G:\\BACKUP");

        ftp.deleteFile("img1.jpg");

        ftp.close();
    }

}
