/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blutzerz.ftpclient;

import java.io.File;
import java.io.IOException;

import javax.swing.filechooser.FileSystemView;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    

    public static void main(String[] args) throws IOException {
        // System.out.println(new App().getGreeting());

        // FTPEngine ftp = new FTPEngine(
        //     "files.000webhost.com", 
        //     21, 
        //     "blutzerz-ftp-client-test", 
        //     "tNb2dRx![2Qw7LUf24");

            
        // ftp.open();
        // ftp.changeDirectory("/public_html");
        // ftp.uploadFile("G:/img1.jpg");
        // for(FTPFile ftpFile : ftp.getFilesDirectory()){
        //     System.out.println(ftpFile.getName());
        // }
        // ftp.downloadFile(".htaccess", "G:\\BACKUP");

        // ftp.deleteFile("img1.jpg");

        // ftp.close();
        FileSystemView view = FileSystemView.getFileSystemView();
        File dir = view.getHomeDirectory();
        File[] files = dir.listFiles();

        
        for (File file : files) {
            System.out.println(file);
        }
        System.out.println("Current Working Directory: " + dir.getAbsolutePath());
        System.setProperty("user.dir", "/home/CODE");
        System.out.println("Now Working Directory: " + dir.getAbsolutePath());
        // files = dir.listFiles();

        // for (File file : files) {
        //     System.out.println(file);
        // }

        File file=new File(".");
        System.out.println("Current Working Directory: " + file.getAbsolutePath());
        System.setProperty("user.dir", "/home/blutzerz");
        System.out.println("New Current Working Directory: " + file.getAbsolutePath());

    }

}
