/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blutzerz.ftpclient;

import java.io.File;
import java.io.IOException;

import javax.swing.filechooser.FileSystemView;

import org.apache.commons.net.ftp.FTPFile;

import com.blutzerz.ftpclient.engine.FTPEngine;
import com.blutzerz.ftpclient.engine.LocalStorageEngine;

public class App {
    public static void main(String[] args) throws IOException {
        LocalStorageEngine localDir = new LocalStorageEngine();
        FTPEngine ftp = new FTPEngine(
                "files.000webhost.com",
                21,
                "blutzerz-ftp-client-test",
                "tNb2dRx![2Qw7LUf24");

        ftp.open();
        ftp.changeDirectory("/public_html");
        localDir.changeDirecotry("G:/BACKUP");
        ftp.uploadFile(localDir.getCurrentDirectory() + "/" + "img2.jpg");
        for (FTPFile ftpFile : ftp.getFilesDirectory()) {
            System.out.println(ftpFile.getName());
        }
        ftp.downloadFile(".htaccess", localDir.getCurrentDirectory());

        // ftp.deleteFile("img1.jpg");
        localDir.deleteFile("img2.jpg");

        ftp.close();

    }

}
